Repository pimcore/newsletter-bundle, pull requests merged in 2023-05, with the labels that each got.

#21 🔄 synced file(s) with pimcore/sync-common-files
  .gitattributes
  .github/ci/files/.env
  .github/ci/files/.my.cnf
  .github/ci/files/bin/console
  .github/ci/files/kernel/Kernel.php
  .github/ci/files/public/.htaccess
  .github/ci/files/public/index_test.php
  .github/ci/files/templates/.gitkeep
Labels: sync

#22 [Bug] Fix PO editor sync
  .github/workflows/poeditor-export.yaml
Labels: Bug

#24 [Task] Run Phpstan against stable 11.0.0
  .github/workflows/static-analysis.yml
Labels: Task
